import type { Metadata } from "next";
import "./globals.css";
import "./reset.css";
import Header from "./components/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="flex flex-col h-screen justify-between">
				{/* <header className="text-center text-2xl h-36 mb-auto">Header</header> */}
        <Header />
				<main className="grow">{children}</main>
				<footer className="text-center text-2xl h-36 mt-auto">
					&copy;Ansaks
				</footer>
			</body>
		</html>
	);
}
